/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo1.maven.org/maven2")

        // isAllowInsecureProtocol = true
    }
}

dependencies {
    api("org.jsoup:jsoup:1.7.1")
    api("org.apache.lucene:lucene-core:4.9.0")
    api("org.apache.logging.log4j:log4j:2.14.0")
    api("com.googlecode.json-simple:json-simple:1.1")
    api("com.sun.jersey:jersey-client:1.8")
    api("commons-codec:commons-codec:1.11")
    api("mysql:mysql-connector-java:6.0.5")
    api("org.apache.commons:commons-lang3:3.1")
    api("commons-collections:commons-collections:3.2.2")
    api("com.google.apis:google-api-services-analyticsreporting:v4-rev128-1.25.0")
    api("com.google.guava:guava:12.0")
    api("org.hibernate:hibernate-validator:6.0.13.Final")
    api("org.glassfish:javax.el:3.0.0")
    api("com.fasterxml.jackson.core:jackson-databind:2.9.8")
    api("nl.basjes.parse.useragent:yauaa:7.6.0")
    testImplementation("junit:junit:4.12")
}

group = "com.idrive"
version = "0.0.1-SNAPSHOT"
description = "MyJava"
java.sourceCompatibility = JavaVersion.VERSION_1_9

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
